spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: h2db
    password: root
    # 持久化到磁盘中，放在内存配置为：jdbc:h2:mem:testdb
    url: jdbc:h2:file:D:\testdata\h2db-short-url
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    # 配置 h2 控制台界面
    console:
      # 默认为false关闭控制台
      enabled: true
      path: /h2console
      settings:
        trace: false
        web-allow-others: false
server:
  port: 9091

short-url:
  service: hash