spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://127.0.0.1:5432/test_data?currentSchema=test_data
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
#      authentication-database: admin
#      username: admin
#      password: admin