spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://127.0.0.1:5432/test_data?currentSchema=test_data
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  data:
#    mongodb:
#      host: 127.0.0.1
#      port: 27017
#      database: test
#      authentication-database: admin
#      username: admin
#      password: admin
server:
  port: 9091

#file:
#  storage:
#    type: mongo
#    type: minio
#    url: 127.0.0.1:27017
#    url: 127.0.0.1:9000
#    username: minioadmin
#    password: minioadmin
#    database: test
#    database: C:\Users\zengchzh\Desktop\testFileChannel
#    authentication-db: admin

